# Generated by Django 4.2.4 on 2023-09-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creepybook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
